In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

print(a)

[1 2 3]


In [3]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
list1=[10,20,30,40]
arr=np.array(list1)
arr

array([10, 20, 30, 40])

In [5]:
import pandas as pd

In [6]:
series=pd.Series()
series

C:\Users\azart\AppData\Local\Temp\ipykernel_17876\3653426392.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  series=pd.Series()


Series([], dtype: float64)

In [7]:
arr=np.array([10,20,30,40])
series=pd.Series(arr)
print(series)

0    10
1    20
2    30
3    40
dtype: int32


In [8]:
data={'a':100,'b':200,'c':300}
print(data)
s1=pd.Series(data)
print(s1)

{'a': 100, 'b': 200, 'c': 300}
a    100
b    200
c    300
dtype: int64


In [ ]:
#DataFrame

In [9]:
list1=[10,20,30,40]
table=pd.DataFrame(list1)
table

0
0  10
1  20
2  30
3  40

In [11]:
data=[{"a":101,"b":102,"c":103,"d":104}]
table=pd.DataFrame(data,index=['f1','f2'])
table

a    b    c    d
f1  101  102  103  104
f2  101  102  103  104

In [15]:
data={'One':pd.Series([1,2,3,4],index=['a','b','c','d']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
table=pd.DataFrame(data)
table
table['three']=pd.Series([10,20,30,40],index=['a','b','c','d'])#add the column
print(table)

   One  two  three
a    1    1     10
b    2    2     20
c    3    3     30
d    4    4     40


In [16]:
del table['One']
print(table)

   two  three
a    1     10
b    2     20
c    3     30
d    4     40
